version: "3.5"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - "redis"
    depends_on:
      - redis
    networks:
      - pkid-net
    environment:
      - redis-host=redis

  redis:
    container_name: redis
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - pkid-data:/data
    networks:
      - pkid-net
  
networks:
  pkid-net:
    name: pkid-net

volumes:
  pkid-data:
    name: pkid-data