version: "3.3"
services:
  3proxy:
    image: jimber/3proxy:broker
    container_name: jimber_proxy
    build: ./
    volumes:
      - /var/proxy/certs/:/certificates/
      - /root/proxy/exampledist/dist:/var/www/3botexample
    ports:
     - 80:80
     - 443:443
    networks:
     jimber_proxy:
       aliases:
         - jimber_proxy
     jimber_broker:
       aliases:
         - jimber_broker
networks:
    jimber_proxy:
      external:
        name: jimber_proxy_net
    jimber_broker:
      external:
        name: jimber_broker_net